// Code generated by ent, DO NOT EDIT.

package ent

import (
	"example.com/go-inventory-grpc/ent/schema"
	"example.com/go-inventory-grpc/ent/staff"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	staffFields := schema.Staff{}.Fields()
	_ = staffFields
	// staffDescEmail is the schema descriptor for email field.
	staffDescEmail := staffFields[0].Descriptor()
	// staff.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	staff.EmailValidator = staffDescEmail.Validators[0].(func(string) error)
	// staffDescName is the schema descriptor for name field.
	staffDescName := staffFields[1].Descriptor()
	// staff.DefaultName holds the default value on creation for the name field.
	staff.DefaultName = staffDescName.Default.(string)
}
