// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.1
// source: internal/proto/inventory.proto

package endpoint

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InventoryService_Register_FullMethodName        = "/inventorymanagement.InventoryService/Register"
	InventoryService_CreateStaff_FullMethodName     = "/inventorymanagement.InventoryService/CreateStaff"
	InventoryService_GetAllStaff_FullMethodName     = "/inventorymanagement.InventoryService/GetAllStaff"
	InventoryService_GetStaffById_FullMethodName    = "/inventorymanagement.InventoryService/GetStaffById"
	InventoryService_DeleteStaffById_FullMethodName = "/inventorymanagement.InventoryService/DeleteStaffById"
	InventoryService_UpdateStaffById_FullMethodName = "/inventorymanagement.InventoryService/UpdateStaffById"
	InventoryService_CreateCategory_FullMethodName  = "/inventorymanagement.InventoryService/CreateCategory"
	InventoryService_CreateProduct_FullMethodName   = "/inventorymanagement.InventoryService/CreateProduct"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	Register(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	CreateStaff(ctx context.Context, in *CreateStaffRequest, opts ...grpc.CallOption) (*CreateStaffResponse, error)
	GetAllStaff(ctx context.Context, in *GetAllStaffRequest, opts ...grpc.CallOption) (*GetAllStaffResponse, error)
	GetStaffById(ctx context.Context, in *GetStaffByIdRequest, opts ...grpc.CallOption) (*GetStaffByIdResponse, error)
	DeleteStaffById(ctx context.Context, in *DeleteStaffByIdRequest, opts ...grpc.CallOption) (*DeleteStaffByIdResponse, error)
	UpdateStaffById(ctx context.Context, in *UpdateStaffByIdRequest, opts ...grpc.CallOption) (*UpdateStaffByIdResponse, error)
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) Register(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, InventoryService_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) CreateStaff(ctx context.Context, in *CreateStaffRequest, opts ...grpc.CallOption) (*CreateStaffResponse, error) {
	out := new(CreateStaffResponse)
	err := c.cc.Invoke(ctx, InventoryService_CreateStaff_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetAllStaff(ctx context.Context, in *GetAllStaffRequest, opts ...grpc.CallOption) (*GetAllStaffResponse, error) {
	out := new(GetAllStaffResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetAllStaff_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetStaffById(ctx context.Context, in *GetStaffByIdRequest, opts ...grpc.CallOption) (*GetStaffByIdResponse, error) {
	out := new(GetStaffByIdResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetStaffById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) DeleteStaffById(ctx context.Context, in *DeleteStaffByIdRequest, opts ...grpc.CallOption) (*DeleteStaffByIdResponse, error) {
	out := new(DeleteStaffByIdResponse)
	err := c.cc.Invoke(ctx, InventoryService_DeleteStaffById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) UpdateStaffById(ctx context.Context, in *UpdateStaffByIdRequest, opts ...grpc.CallOption) (*UpdateStaffByIdResponse, error) {
	out := new(UpdateStaffByIdResponse)
	err := c.cc.Invoke(ctx, InventoryService_UpdateStaffById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	out := new(CreateCategoryResponse)
	err := c.cc.Invoke(ctx, InventoryService_CreateCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, InventoryService_CreateProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility
type InventoryServiceServer interface {
	Register(context.Context, *Message) (*Message, error)
	CreateStaff(context.Context, *CreateStaffRequest) (*CreateStaffResponse, error)
	GetAllStaff(context.Context, *GetAllStaffRequest) (*GetAllStaffResponse, error)
	GetStaffById(context.Context, *GetStaffByIdRequest) (*GetStaffByIdResponse, error)
	DeleteStaffById(context.Context, *DeleteStaffByIdRequest) (*DeleteStaffByIdResponse, error)
	UpdateStaffById(context.Context, *UpdateStaffByIdRequest) (*UpdateStaffByIdResponse, error)
	CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error)
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInventoryServiceServer struct {
}

func (UnimplementedInventoryServiceServer) Register(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedInventoryServiceServer) CreateStaff(context.Context, *CreateStaffRequest) (*CreateStaffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStaff not implemented")
}
func (UnimplementedInventoryServiceServer) GetAllStaff(context.Context, *GetAllStaffRequest) (*GetAllStaffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllStaff not implemented")
}
func (UnimplementedInventoryServiceServer) GetStaffById(context.Context, *GetStaffByIdRequest) (*GetStaffByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStaffById not implemented")
}
func (UnimplementedInventoryServiceServer) DeleteStaffById(context.Context, *DeleteStaffByIdRequest) (*DeleteStaffByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStaffById not implemented")
}
func (UnimplementedInventoryServiceServer) UpdateStaffById(context.Context, *UpdateStaffByIdRequest) (*UpdateStaffByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStaffById not implemented")
}
func (UnimplementedInventoryServiceServer) CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedInventoryServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).Register(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_CreateStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateStaff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateStaff(ctx, req.(*CreateStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetAllStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetAllStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetAllStaff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetAllStaff(ctx, req.(*GetAllStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetStaffById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStaffByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetStaffById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetStaffById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetStaffById(ctx, req.(*GetStaffByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_DeleteStaffById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStaffByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).DeleteStaffById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_DeleteStaffById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).DeleteStaffById(ctx, req.(*DeleteStaffByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_UpdateStaffById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStaffByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).UpdateStaffById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_UpdateStaffById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).UpdateStaffById(ctx, req.(*UpdateStaffByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventorymanagement.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _InventoryService_Register_Handler,
		},
		{
			MethodName: "CreateStaff",
			Handler:    _InventoryService_CreateStaff_Handler,
		},
		{
			MethodName: "GetAllStaff",
			Handler:    _InventoryService_GetAllStaff_Handler,
		},
		{
			MethodName: "GetStaffById",
			Handler:    _InventoryService_GetStaffById_Handler,
		},
		{
			MethodName: "DeleteStaffById",
			Handler:    _InventoryService_DeleteStaffById_Handler,
		},
		{
			MethodName: "UpdateStaffById",
			Handler:    _InventoryService_UpdateStaffById_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _InventoryService_CreateCategory_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _InventoryService_CreateProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/inventory.proto",
}
