// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// OrderDetails is the predicate function for orderdetails builders.
type OrderDetails func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Staff is the predicate function for staff builders.
type Staff func(*sql.Selector)
